class Autogenerated {
  int? statusCode;
  String? statusMessage;
  List<Response_Message>? response;

  Autogenerated({this.statusCode, this.statusMessage, this.response});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code'];
    statusMessage = json['status_message'];
    if (json['response'] != null) {
      response = <Response_Message>[];
      json['response'].forEach((v) {
        response!.add(new Response_Message.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status_code'] = this.statusCode;
    data['status_message'] = this.statusMessage;
    if (this.response != null) {
      data['response'] = this.response!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Response_Message {
  int? id;
  String? chatId;
  String? chatHisIds;
  String? senderId;
  String? sendMsg;
  String? date;
  String? time;
  String? createdAt;
  Null? updatedAt;
  String? trashStatus;

  Response_Message(
      {this.id,
      this.chatId,
      this.chatHisIds,
      this.senderId,
      this.sendMsg,
      this.date,
      this.time,
      this.createdAt,
      this.updatedAt,
      this.trashStatus});

  Response_Message.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    chatId = json['chat_id'];
    chatHisIds = json['chat_his_ids'];
    senderId = json['sender_id'];
    sendMsg = json['send_msg'];
    date = json['date'];
    time = json['time'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    trashStatus = json['trash_status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['chat_id'] = this.chatId;
    data['chat_his_ids'] = this.chatHisIds;
    data['sender_id'] = this.senderId;
    data['send_msg'] = this.sendMsg;
    data['date'] = this.date;
    data['time'] = this.time;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['trash_status'] = this.trashStatus;
    return data;
  }
}